services:
    impedanz-web:
        image: 127.0.0.1:5000/impedanz-web
        container_name: impedanz-web
        restart: always
        networks:
            - rp
        labels:
            traefik.enable: "true"
            traefik.http.routers.impedanz-web.tls.certresolver: "default"
            traefik.http.routers.impedanz-web.tls.domains[0].main: "impedanz.net"
            traefik.http.routers.impedanz-web.tls.domains[0].sans: "*.impedanz.net"
            traefik.http.routers.impedanz-web.rule: "Host(`www.impedanz.net`) || Host(`impedanz.net`)"
            traefik.http.routers.impedanz-web.entrypoints: "websecure"
            traefik.http.services.impedanz-web.loadbalancer.server.port: "80"
            traefik.docker.network: rp
            com.centurylinklabs.watchtower.enable: true
            turing.public:
networks:
    rp:
        name: rp

